services:
  GolangApiServer:
    image: chenmonkey438/go-app-api
    restart: unless-stopped
    container_name: GolangApiServer
    environment:
      - MONGO_URI=mongodb://admin:123456@mongodb:27017/?authSource=admin
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
  VueServer:
    image: chenmonkey438/vue-app-fe
    container_name: VueServer
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - dist:/dist
    depends_on:
      - GolangApiServer

  mongodb:
    container_name: mongodb
    image: mongo:7.0
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet -u admin -p 123456 --authenticationDatabase admin --eval \"quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)\""]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - app-network


volumes:
  dist:
    driver: local
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge