name: 'Setup Frontend Environment'
description: 'Sets up Node env and install frontend dependencies'

runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 11.7.0
        run_install: false
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '24.15.0'
        cache: 'pnpm'
        cache-dependency-path: './frontend/pnpm-lock.yaml'
    - name: Install Node dependencies
      run: pnpm install --frozen-lockfile
      working-directory: ./frontend
      shell: bash

    - name: Build Vue App
      run: pnpm run build
      working-directory: ./frontend
      shell: bash
