// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: protos/Notification.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationGrpcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	XId           string                 `protobuf:"bytes,1,opt,name=_id,json=Id,proto3" json:"_id,omitempty"`
	Details       string                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	MainUserId    string                 `protobuf:"bytes,3,opt,name=mainUserId,proto3" json:"mainUserId,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=targetId,proto3" json:"targetId,omitempty"`
	IsRead        bool                   `protobuf:"varint,5,opt,name=isRead,proto3" json:"isRead,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	User          *Usergrpc              `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationGrpcRequest) Reset() {
	*x = NotificationGrpcRequest{}
	mi := &file_protos_Notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationGrpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationGrpcRequest) ProtoMessage() {}

func (x *NotificationGrpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationGrpcRequest.ProtoReflect.Descriptor instead.
func (*NotificationGrpcRequest) Descriptor() ([]byte, []int) {
	return file_protos_Notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationGrpcRequest) GetXId() string {
	if x != nil {
		return x.XId
	}
	return ""
}

func (x *NotificationGrpcRequest) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *NotificationGrpcRequest) GetMainUserId() string {
	if x != nil {
		return x.MainUserId
	}
	return ""
}

func (x *NotificationGrpcRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NotificationGrpcRequest) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *NotificationGrpcRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NotificationGrpcRequest) GetUser() *Usergrpc {
	if x != nil {
		return x.User
	}
	return nil
}

type Usergrpc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Usergrpc) Reset() {
	*x = Usergrpc{}
	mi := &file_protos_Notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usergrpc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usergrpc) ProtoMessage() {}

func (x *Usergrpc) ProtoReflect() protoreflect.Message {
	mi := &file_protos_Notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usergrpc.ProtoReflect.Descriptor instead.
func (*Usergrpc) Descriptor() ([]byte, []int) {
	return file_protos_Notification_proto_rawDescGZIP(), []int{1}
}

func (x *Usergrpc) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Usergrpc) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

var File_protos_Notification_proto protoreflect.FileDescriptor

const file_protos_Notification_proto_rawDesc = "" +
	"\n" +
	"\x19protos/Notification.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf1\x01\n" +
	"\x17NotificationGrpcRequest\x12\x0f\n" +
	"\x03_id\x18\x01 \x01(\tR\x02Id\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails\x12\x1e\n" +
	"\n" +
	"mainUserId\x18\x03 \x01(\tR\n" +
	"mainUserId\x12\x1a\n" +
	"\btargetId\x18\x04 \x01(\tR\btargetId\x12\x16\n" +
	"\x06isRead\x18\x05 \x01(\bR\x06isRead\x128\n" +
	"\tcreatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\x04user\x18\a \x01(\v2\t.UsergrpcR\x04user\"6\n" +
	"\bUsergrpc\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar2c\n" +
	"\x17NotificationGrpcService\x12H\n" +
	"\x14SendGrpcNotification\x12\x18.NotificationGrpcRequest\x1a\x16.google.protobuf.EmptyB\tZ\a/protosb\x06proto3"

var (
	file_protos_Notification_proto_rawDescOnce sync.Once
	file_protos_Notification_proto_rawDescData []byte
)

func file_protos_Notification_proto_rawDescGZIP() []byte {
	file_protos_Notification_proto_rawDescOnce.Do(func() {
		file_protos_Notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_Notification_proto_rawDesc), len(file_protos_Notification_proto_rawDesc)))
	})
	return file_protos_Notification_proto_rawDescData
}

var file_protos_Notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_Notification_proto_goTypes = []any{
	(*NotificationGrpcRequest)(nil), // 0: NotificationGrpcRequest
	(*Usergrpc)(nil),                // 1: Usergrpc
	(*timestamppb.Timestamp)(nil),   // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 3: google.protobuf.Empty
}
var file_protos_Notification_proto_depIdxs = []int32{
	2, // 0: NotificationGrpcRequest.createdAt:type_name -> google.protobuf.Timestamp
	1, // 1: NotificationGrpcRequest.user:type_name -> Usergrpc
	0, // 2: NotificationGrpcService.SendGrpcNotification:input_type -> NotificationGrpcRequest
	3, // 3: NotificationGrpcService.SendGrpcNotification:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_Notification_proto_init() }
func file_protos_Notification_proto_init() {
	if File_protos_Notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_Notification_proto_rawDesc), len(file_protos_Notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_Notification_proto_goTypes,
		DependencyIndexes: file_protos_Notification_proto_depIdxs,
		MessageInfos:      file_protos_Notification_proto_msgTypes,
	}.Build()
	File_protos_Notification_proto = out.File
	file_protos_Notification_proto_goTypes = nil
	file_protos_Notification_proto_depIdxs = nil
}
