name: "Setup Backend Environment"
description: "Sets up Go env and install backend dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up to
      uses: actions/setup-go@v4
      with:
        go-version: "1.26.1"

    - name: Cache Go Modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Install dependencies
      run: |
        go mod tidy
        go mod download
      working-directory: ./backend/api
      shell: bash

    - name: Install test Dependencies
      run: go get -t ./tests/...
      working-directory: ./backend/api
      shell: bash
